### ISSUE TITLE
Backfill from earliest-> latest; also small Kraken things

### ISSUE THREAD

**Issue by nateGeorge** [bmoscon/cryptostore#35]
In the demo config.yaml file, [it says](https://github.com/bmoscon/cryptostore/blob/master/config.yaml#L112):

```
# If configured, backfill will run in a separate process and
# backfill trade data from the specifed start date, until it finds existing data
# in the storage medium.
```

However, the actual backfilling happens in reverse -- it starts with the current date and goes backwards.  Every time the backfill process is started, it restarts from the current date and fills all the way to the start date.  Here's an example from backfilling Kraken data:

```
2019-08-07 23:54:00,053 : INFO : Backfill - Reading 2015-01-04 00:00:00 to 2015-01-04 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:02,002 : INFO : Backfill - Wrote 2015-01-04 00:00:00 to 2015-01-04 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:02,002 : INFO : Backfill - Reading 2015-01-03 00:00:00 to 2015-01-03 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:04,368 : INFO : Backfill - Wrote 2015-01-03 00:00:00 to 2015-01-03 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:04,369 : INFO : Backfill - Reading 2015-01-02 00:00:00 to 2015-01-02 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:06,393 : INFO : Backfill - Wrote 2015-01-02 00:00:00 to 2015-01-02 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:06,393 : INFO : Backfill - Reading 2015-01-01 00:00:00 to 2015-01-01 23:59:59.999999999 for KRAKEN - DASH-USD
2019-08-07 23:54:08,914 : INFO : Backfill - Wrote 2015-01-01 00:00:00 to 2015-01-01 23:59:59.999999999 for KRAKEN - DASH-USD
```

I think a better way would be to start with the start date and fill up to the present time as described in the config file.  Possibly even better would be to track the latest date that has been backfilled (perhaps in another storage dataset), so the backfiller can start there just in case there is any missing data from live-recording.  Seems like around [here](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/plugin/backfill.py#L36) could be used to check for the latest backfill date to start from.  Then around [here](https://github.com/bmoscon/cryptostore/blob/master/cryptostore/plugin/backfill.py#L79) when the backfill is completed we could write the latest backfill date to another datastore.

With Kraken, we should be able to use the latest timestamp from retrieved historical data for the start of the next query.  In cryptofeed, it seems to be [the case](https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/rest/kraken.py#L182).  But in cryptostore, we are getting one day at a time, and moving backwards in time.

For Kraken, we can also get the earliest timestamp by sending a '0' for the start time.  I think it would be nice to have the ability to put 'earliest' in the backfill 'start' parameter to have the data start at the earliest possible time (and/or put 0 or another keyword).  I'm not sure for how many other exchanges this works, but I think also Poloniex at least.

**Comment by bmoscon** [comment]
I've updated the config so its clearer. its significantly easier to make the code restartable if it goes from earliest written data until start date (working backwards) since its very easy to get the earliest date out of the storage engines. Because there isnt a forced way to store the data, aggregate, etc its not feasible (in my opinion) to store the last written data date without adding something like sqllite, which I'd prefer not to do.

**Comment by nateGeorge** [comment]
I see.  The issue I'm encountering is it restarts the backfill every time and starts from the latest date and then fills over any existing data.  From my experience, it doesn't seem to be working correctly.  Shouldn't it be filling back to any data that exists, then getting the earliest and trying to backfill from there?

**Comment by bmoscon** [comment]
@nateGeorge it should not overwrite anything thats already been written. It could be an issue with the data - if a timestamp was not stored correctly that would cause an issue. I'm working on some major changes to this so once thats done i'll confirm its working as intended with kraken - i know it works with most the other exchanges i use

**Comment by nateGeorge** [comment]
Ok, I should try with another exchange, but as I said it seemed to be an issue with Coinbase as well.  How would it work with a gap in between the latest backfilled data and the newest data?  Example: if it backfilled from 8-20-2019 to the earliest timestamp, then we collected some data live on 8-22-2019, when we backfill next would it start from today and go to 8-20 or go to 8-22?

**Comment by bmoscon** [comment]
i released the new backfiller. I tested it several times over several days, it works for me. You'll probably need to start with a clean datastore as many things have changed and not everything is backwards compatible, there were also bugs that have been fixed that stored data with the incorrect timestamp that could affect backfill. If it still doesnt work for you, please send me the config you're using so I can try and replicate the issue on my end. I'll close this in a few days if I dont hear anything back as its all working for me as intended

**Comment by nateGeorge** [comment]
I'll have to try again.  I thought I had just tested a few days ago and still seeing the same issues.  I still think it makes more sense to start at either the earliest timestamp (usually putting in a 0 for the timestamp when fetching data gets the earliest time) and work up to present.  Then storing the latest backfilled data in a db entry so it knows where it's backfilled up to.  I'll have to make sure I'm using the latest version and test again.
